/**
 * Content bank — inventories every blog post for social repurposing.
 *
 * Reads `src/content/posts/*.md` and writes `docs/content-bank.md`: for each
 * post, the hook (first paragraph), the H2s, numbered-list items (carousel and
 * thread material), quotable lines (bold one-liners, blockquotes), word count
 * and a guess at the post's shape (story / list / thesis).
 *
 * Read-only against the posts. No dependencies. Run:
 *
 *   node scripts/content-bank.mjs
 *
 * See `docs/05-content-engine.md` for how the bank is used.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const POSTS_DIR = path.resolve('src/content/posts');
const OUT = path.resolve('docs/content-bank.md');

/** Minimal frontmatter reader: `key: "value"` / `key: value` pairs only. */
function parseFrontmatter(src) {
  const m = src.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!m) return { data: {}, body: src };
  const data = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^(\w+):\s*(.*)$/);
    if (!kv) continue;
    let v = kv[2].trim();
    if (/^".*"$/.test(v)) v = v.slice(1, -1);
    data[kv[1]] = v;
  }
  return { data, body: m[2] };
}

/** Strip inline markdown so the bank reads as plain sentences. */
function plain(s) {
  return s
    .replace(/!\[[^\]]*\]\([^)]*\)/g, '')
    .replace(/\[([^\]]+)\]\([^)]*\)/g, '$1')
    .replace(/[*_`]+/g, '')
    .replace(/&amp;/g, '&')
    .replace(/\s+/g, ' ')
    .trim();
}

function truncate(s, n) {
  return s.length <= n ? s : `${s.slice(0, n - 1).replace(/\s+\S*$/, '')}…`;
}

function analyse(file, src) {
  const { data, body } = parseFrontmatter(src);
  const lines = body.split(/\r?\n/);

  const paragraphs = [];
  const h2s = [];
  const numbered = [];
  const bullets = [];
  const quotes = [];

  for (const raw of lines) {
    const line = raw.trim();
    if (!line || line === '---') continue;

    if (/^## /.test(line)) {
      h2s.push(plain(line.slice(3)));
      continue;
    }
    if (/^#{1,6} /.test(line)) continue;

    const num = line.match(/^\d+\.\s+(.*)$/);
    if (num) {
      // Prefer the bolded lead of a numbered item; it is usually the point.
      const lead = num[1].match(/^\*\*([^*]+)\*\*/);
      numbered.push(plain(lead ? lead[1] : truncate(num[1], 90)));
      continue;
    }
    const bul = line.match(/^[-*]\s+(.*)$/);
    if (bul) {
      const lead = bul[1].match(/^\*\*([^*]+)\*\*/);
      bullets.push(plain(lead ? lead[1] : truncate(bul[1], 90)));
      continue;
    }
    if (/^>\s?/.test(line)) {
      quotes.push(plain(line.replace(/^>\s?/, '')));
      continue;
    }
    // A whole line set in bold (or bold-italic) is John's own pull-quote.
    if (/^\*\*_?[^*]+_?\*\*$/.test(line) || /^_\*\*[^*]+\*\*_$/.test(line)) {
      quotes.push(plain(line));
      continue;
    }
    paragraphs.push(line);
  }

  const words = plain(paragraphs.join(' ')).split(' ').filter(Boolean).length;
  const hook = plain(paragraphs[0] ?? '');
  const closing = plain(paragraphs.at(-1) ?? '');

  // Shape: what the post is built from decides which formats it feeds.
  let shape = 'thesis';
  if (numbered.length >= 3) shape = 'list';
  else if (/^(I|My|We|When I|Last|This|Today|Growing up)\b/.test(hook) && /\b(I|my|me)\b/.test(hook)) shape = 'story';

  // De-duplicate quotable lines and drop anything that is not a sentence.
  const quotable = [...new Set(quotes)].filter((q) => {
    if (q.length < 15 || q.length > 220) return false;
    if (/^\d+\.\s/.test(q)) return false; // a bolded list heading, not a line
    const isSentence = /[.?!"”]$/.test(q);
    const wordCount = q.split(' ').length;
    return isSentence || wordCount >= 7; // short unpunctuated lines are headings
  });

  return {
    file,
    slug: file.replace(/\.md$/, ''),
    title: data.title ?? file,
    description: data.description ?? '',
    date: data.pubDate ?? '',
    category: data.category ?? '',
    draft: data.draft === 'true',
    words,
    shape,
    hook,
    closing,
    h2s,
    numbered,
    bullets,
    quotable,
  };
}

function render(posts) {
  const byShape = { story: 0, list: 0, thesis: 0 };
  const byCat = {};
  let quoteTotal = 0;
  let numberedPosts = 0;
  for (const p of posts) {
    byShape[p.shape]++;
    byCat[p.category] = (byCat[p.category] ?? 0) + 1;
    quoteTotal += p.quotable.length;
    if (p.numbered.length >= 3) numberedPosts++;
  }

  const out = [];
  out.push('# Content bank');
  out.push('');
  out.push('Generated by `scripts/content-bank.mjs` from `src/content/posts/`. Do not edit');
  out.push('by hand; re-run the script. How to use it: `docs/05-content-engine.md`.');
  out.push('');
  out.push('## Totals');
  out.push('');
  out.push('| | |');
  out.push('|---|---|');
  out.push(`| Posts | ${posts.length} |`);
  out.push(`| Story-shaped | ${byShape.story} |`);
  out.push(`| List-shaped (3+ numbered items) | ${byShape.list} |`);
  out.push(`| Thesis-shaped | ${byShape.thesis} |`);
  out.push(`| Posts with a numbered list (carousel or thread ready) | ${numberedPosts} |`);
  out.push(`| Quotable lines (bold one-liners and blockquotes) | ${quoteTotal} |`);
  out.push(`| Subheads (H2) | ${posts.reduce((n, p) => n + p.h2s.length, 0)} |`);
  out.push('');
  out.push('By category: ' + Object.entries(byCat).sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k} ${v}`).join(' · '));
  out.push('');
  out.push('## Index');
  out.push('');
  out.push('| Date | Category | Shape | Words | Quotes | Numbered | Title |');
  out.push('|---|---|---|---|---|---|---|');
  for (const p of posts) {
    out.push(`| ${p.date} | ${p.category} | ${p.shape} | ${p.words} | ${p.quotable.length} | ${p.numbered.length} | [${p.title}](#${p.slug}) |`);
  }
  out.push('');
  out.push('## Posts');
  out.push('');
  for (const p of posts) {
    out.push(`### ${p.title}`);
    out.push('');
    out.push(`<a id="${p.slug}"></a>`);
    out.push('');
    out.push(`\`${p.slug}\` · ${p.date} · ${p.category} · ${p.shape} · ${p.words} words${p.draft ? ' · draft' : ''}`);
    out.push('');
    if (p.description) {
      out.push(`**Meta description.** ${p.description}`);
      out.push('');
    }
    if (p.hook) {
      out.push(`**Hook (first paragraph).** ${truncate(p.hook, 300)}`);
      out.push('');
    }
    if (p.h2s.length) {
      out.push('**Subheads.**');
      for (const h of p.h2s) out.push(`- ${h}`);
      out.push('');
    }
    if (p.numbered.length) {
      out.push('**Numbered list.**');
      p.numbered.forEach((n, i) => out.push(`${i + 1}. ${n}`));
      out.push('');
    }
    if (p.bullets.length) {
      out.push(`**Bullets (${p.bullets.length}).**`);
      for (const b of p.bullets.slice(0, 8)) out.push(`- ${b}`);
      if (p.bullets.length > 8) out.push(`- … ${p.bullets.length - 8} more`);
      out.push('');
    }
    if (p.quotable.length) {
      out.push('**Quotable.**');
      for (const q of p.quotable) out.push(`> ${q}`);
      out.push('');
    }
    if (p.closing) {
      out.push(`**Closing line.** ${truncate(p.closing, 240)}`);
      out.push('');
    }
  }
  return out.join('\n') + '\n';
}

const files = (await readdir(POSTS_DIR)).filter((f) => f.endsWith('.md')).sort();
const posts = [];
for (const f of files) {
  posts.push(analyse(f, await readFile(path.join(POSTS_DIR, f), 'utf8')));
}
posts.sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));

await writeFile(OUT, render(posts));
console.log(`content bank: ${posts.length} posts → ${path.relative(process.cwd(), OUT)}`);
